
package com.example.myproject;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HiHelloWS", targetNamespace = "http://demo.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HiHelloWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://demo.example.com/", className = "com.example.myproject.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://demo.example.com/", className = "com.example.myproject.SayHelloResponse")
    public String sayHello();

}
