
package com.example.myproject;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HiHelloWSService", targetNamespace = "http://demo.example.com/", wsdlLocation = "http://localhost:8084/?wsdl")
public class HiHelloWSService
    extends Service
{

    private final static URL HIHELLOWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.example.myproject.HiHelloWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.example.myproject.HiHelloWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8084/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8084/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HIHELLOWSSERVICE_WSDL_LOCATION = url;
    }

    public HiHelloWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HiHelloWSService() {
        super(HIHELLOWSSERVICE_WSDL_LOCATION, new QName("http://demo.example.com/", "HiHelloWSService"));
    }

    /**
     * 
     * @return
     *     returns HiHelloWS
     */
    @WebEndpoint(name = "HiHelloWSPort")
    public HiHelloWS getHiHelloWSPort() {
        return super.getPort(new QName("http://demo.example.com/", "HiHelloWSPort"), HiHelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiHelloWS
     */
    @WebEndpoint(name = "HiHelloWSPort")
    public HiHelloWS getHiHelloWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.example.com/", "HiHelloWSPort"), HiHelloWS.class, features);
    }

}
